---
- block:
  - name: Make sure git is installed as it is required by git_config module
    yum: name=git state=present

  - name: Include git variable file
    include_vars: "git.yml"

  - name: Configure system git
    git_config:
      name: "{{ item.0.section }}.{{ item.1.name }}"
      value: "{{ item.1.value }}"
      scope: system
    with_subelements:
      - "{{ system_git_configs }}"
      - config
  become: True
  become_user: root

- block:
  - name: Configure local git
    git_config:
      name: "{{ item.0.section }}.{{ item.1.name }}"
      value: "{{ item.1.value }}"
      scope: global
    with_subelements:
      - "{{ user_git_configs }}"
      - config
  become: False
