---
# handlers file for adipriyantobpn.common
- name: restart crond
  become: True
  service:
    name: crond
    state: restarted

- name: reboot message
  debug:
    msg: Please reboot server to make SELinux configuration changes can take effects